package carrerasejbcliente.screens.forms;

import carrerasejbcliente.model.beans.Alumno;

/**
 *
 * @author Rafael Landa
 */
public class VCRUDAlumnos extends javax.swing.JFrame {

    public static javax.swing.table.DefaultTableModel modeloTabla;
    
    private VFormAgregarAlumnos formAgregarAlumnos;
    
    private int indexRowTable;
    
    public VCRUDAlumnos() {
        initTable(new String[]{
            "Matricula", 
            "Nombre Alumno", 
            "Apellido Paterno", 
            "Apellido Materno"
        });
        initComponents();
        initEvents();
        this.setLocation(430, 150);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        panelEditor = new javax.swing.JPanel();
        lbCarrera = new javax.swing.JLabel();
        lbNombreCarrera = new javax.swing.JLabel();
        tabEditor = new javax.swing.JTabbedPane();
        panelEditorAlumnos = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMatricula = new javax.swing.JTextField();
        txtNombreAlumno = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtApellidoPaterno = new javax.swing.JTextField();
        txtApellidoMaterno = new javax.swing.JTextField();
        panelVista = new javax.swing.JPanel();
        scrllTablaVista = new javax.swing.JScrollPane();
        tbAlumnos = new javax.swing.JTable();
        txtBuscarFormat = new javax.swing.JFormattedTextField();
        btnBuscar = new javax.swing.JButton();
        btnActualizarListaAlumnos = new javax.swing.JButton();
        btnBorrarAlumno = new javax.swing.JButton();
        btnAgregarCarrera = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modificación de alumnos");
        setResizable(false);

        lbCarrera.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbCarrera.setText("Carrera: ");

        lbNombreCarrera.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbNombreCarrera.setText("Nombre carrera");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Matricula:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Nombre de alumno:");

        txtMatricula.setEnabled(false);

        txtNombreAlumno.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Apellido paterno:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Apellido materno:");

        txtApellidoPaterno.setEnabled(false);

        txtApellidoMaterno.setEnabled(false);

        javax.swing.GroupLayout panelEditorAlumnosLayout = new javax.swing.GroupLayout(panelEditorAlumnos);
        panelEditorAlumnos.setLayout(panelEditorAlumnosLayout);
        panelEditorAlumnosLayout.setHorizontalGroup(
            panelEditorAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEditorAlumnosLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panelEditorAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEditorAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMatricula)
                    .addComponent(txtNombreAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
                    .addComponent(txtApellidoPaterno)
                    .addComponent(txtApellidoMaterno))
                .addContainerGap())
        );
        panelEditorAlumnosLayout.setVerticalGroup(
            panelEditorAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEditorAlumnosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEditorAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEditorAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNombreAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEditorAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEditorAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        tabEditor.addTab("Datos Alumno:", panelEditorAlumnos);

        tbAlumnos.setModel(modeloTabla);
        tbAlumnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbAlumnosMouseClicked(evt);
            }
        });
        scrllTablaVista.setViewportView(tbAlumnos);

        btnBuscar.setText("Buscar");
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMouseClicked(evt);
            }
        });

        btnActualizarListaAlumnos.setText("Actualizar");

        btnBorrarAlumno.setText("Borrar");
        btnBorrarAlumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBorrarAlumnoMouseClicked(evt);
            }
        });

        btnAgregarCarrera.setText("Agregar");
        btnAgregarCarrera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarCarreraMouseClicked(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelVistaLayout = new javax.swing.GroupLayout(panelVista);
        panelVista.setLayout(panelVistaLayout);
        panelVistaLayout.setHorizontalGroup(
            panelVistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVistaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelVistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrllTablaVista)
                    .addGroup(panelVistaLayout.createSequentialGroup()
                        .addComponent(txtBuscarFormat, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnActualizarListaAlumnos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBorrarAlumno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAgregarCarrera)))
                .addContainerGap())
            .addGroup(panelVistaLayout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelVistaLayout.setVerticalGroup(
            panelVistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVistaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelVistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelVistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtBuscarFormat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelVistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAgregarCarrera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBorrarAlumno)
                        .addComponent(btnActualizarListaAlumnos)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrllTablaVista, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancelar)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelEditorLayout = new javax.swing.GroupLayout(panelEditor);
        panelEditor.setLayout(panelEditorLayout);
        panelEditorLayout.setHorizontalGroup(
            panelEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEditorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabEditor)
                    .addGroup(panelEditorLayout.createSequentialGroup()
                        .addComponent(lbCarrera)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbNombreCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(panelVista, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelEditorLayout.setVerticalGroup(
            panelEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEditorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCarrera)
                    .addComponent(lbNombreCarrera, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabEditor, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelVista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelEditor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelEditor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnCancelarMouseClicked

    private void btnAgregarCarreraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarCarreraMouseClicked
        this.formAgregarAlumnos = new VFormAgregarAlumnos();
        this.formAgregarAlumnos.setVisible(true);
    }//GEN-LAST:event_btnAgregarCarreraMouseClicked

    private void btnBorrarAlumnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBorrarAlumnoMouseClicked
        if (this.btnBorrarAlumno.isEnabled()) {
            if (modeloTabla.getRowCount() > 0) {
                int row = tbAlumnos.rowAtPoint(evt.getPoint());
                if (row >= 0) {
                    int eleccion = 
                        javax.swing.JOptionPane.showOptionDialog(this,
                            "¿Está seguro de eliminar el alumno '" +
                                modeloTabla.getValueAt(row, 1) + "'?",
                                "Mensaje de Confirmacion",
                            javax.swing.JOptionPane.YES_NO_OPTION, 
                            javax.swing.JOptionPane.QUESTION_MESSAGE,
                            null, new Object[] {"Aceptar", "Cancelar"}, 
                            "Aceptar"
                        );
                    if (eleccion == javax.swing.JOptionPane.YES_OPTION)
                        modeloTabla.removeRow(this.getIndexRowTable());
                }
            }
        }
    }//GEN-LAST:event_btnBorrarAlumnoMouseClicked

    private void tbAlumnosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbAlumnosMouseClicked
        int row = tbAlumnos.rowAtPoint(evt.getPoint());
        if (row >= 0) {
            this.setIndexRowTable(row);
            Alumno alumno = new Alumno();
            alumno.setMatricula(modeloTabla.getValueAt(row, 0).toString());
            alumno.setNombreAlumno(modeloTabla.getValueAt(row, 1).toString());
            alumno.setApellidoPaterno(modeloTabla.getValueAt(row, 2).toString());
            alumno.setApellidoMaterno(modeloTabla.getValueAt(row, 3).toString());
            this.txtMatricula.setText(alumno.getMatricula());
            this.txtNombreAlumno.setText(alumno.getNombreAlumno());
            this.txtApellidoPaterno.setText(alumno.getApellidoPaterno());
            this.txtApellidoMaterno.setText(alumno.getApellidoMaterno());
        }
    }//GEN-LAST:event_tbAlumnosMouseClicked

    private void btnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseClicked
        
    }//GEN-LAST:event_btnBuscarMouseClicked

    private void initEvents() {
        this.btnBorrarAlumno.setEnabled(false);
        this.btnActualizarListaAlumnos.setEnabled(false);
    }
    
    private void initTable(String[] columns) {
        VCRUDAlumnos.modeloTabla = new javax.swing.table.DefaultTableModel();
        for (String column : columns)
            modeloTabla.addColumn(column);
        addRowsTable();
    }
    
    private void updateObjectsWhenRowSelected() {
        
    }
    
    private void addRowsTable() {
        modeloTabla.addRow(new Object[] {
            "2015674365", "Nombre", "Apellido Paterno", "Apellido Materno"
        });
        modeloTabla.addRow(new Object[] {
            "2015674365", "Nombre", "Apellido Paterno", "Apellido Materno"
        });
        modeloTabla.addRow(new Object[] {
            "2015674365", "Nombre", "Apellido Paterno", "Apellido Materno"
        });
        modeloTabla.addRow(new Object[] {
            "2015674365", "Nombre", "Apellido Paterno", "Apellido Materno"
        });
        modeloTabla.addRow(new Object[] {
            "2015674365", "Nombre", "Apellido Paterno", "Apellido Materno"
        });
        modeloTabla.addRow(new Object[] {
            "2015674365", "Nombre", "Apellido Paterno", "Apellido Materno"
        });
        modeloTabla.addRow(new Object[] {
            "2015674365", "Nombre", "Apellido Paterno", "Apellido Materno"
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarListaAlumnos;
    private javax.swing.JButton btnAgregarCarrera;
    private javax.swing.JButton btnBorrarAlumno;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbCarrera;
    private javax.swing.JLabel lbNombreCarrera;
    private javax.swing.JPanel panelEditor;
    private javax.swing.JPanel panelEditorAlumnos;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelVista;
    private javax.swing.JScrollPane scrllTablaVista;
    private javax.swing.JTabbedPane tabEditor;
    private javax.swing.JTable tbAlumnos;
    private javax.swing.JTextField txtApellidoMaterno;
    private javax.swing.JTextField txtApellidoPaterno;
    private javax.swing.JFormattedTextField txtBuscarFormat;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtNombreAlumno;
    // End of variables declaration//GEN-END:variables

    public void setlbNombreCarrera(String value) {
        this.lbNombreCarrera.setText(value);
    }

    public int getIndexRowTable() {
        return indexRowTable;
    }

    public void setIndexRowTable(int indexRowTable) {
        this.indexRowTable = indexRowTable;
    }

}
